version: '3'
services:
  fetcher:
    restart: 'always'
    build: ./tracker-fetcher
    networks:
      - redis-net
    depends_on:
      - redis
    volumes:
      - ./tracker-fetcher:/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - MAKER_URL=https://dai-service.makerdao.com/cups
    command: ["yarn", "start"]
  api:
    build: ./tracker-service
    restart: 'always'
    ports:
      - 3001:3000
    networks:
      - redis-net
      - tracker-net
    depends_on:
      - redis
    volumes:
      - ./tracker-service:/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    command: ["yarn", "run", "dev"]
  ui:
    build: ./tracker-ui
    volumes:
      - './tracker-ui:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3000
    networks:
      - tracker-net
    command: ["yarn", "start"]

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - ./redis-data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - redis-net

networks:
  redis-net:
  tracker-net:

volumes:
  redis-data: